on:
    push:
        branches:
            - master
            - main
        paths:
            - 's3/**'
    pull_request:
        paths:
            - 's3/**'
name: "Tests S3"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
        -   name: Install MinIO
            run: docker run -d -p 9000:9000 --name minio minio/minio server /data
        -   name: Fetch Repository
            uses: actions/checkout@v4
        -   name: Install Go
            uses: actions/setup-go@v4
            with:
                go-version: '${{ matrix.go-version }}'
        -   name: Run Test
            run: cd ./s3 && go test ./... -v -race
